name: Cleanup old branches
on:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.1
        with:
          repo_token: ${{ github.token }}
          date: '2 weeks ago'
          dry_run: false
          delete_tags: false
